module.exports=function(e){var t={};function r(a){if(t[a])return t[a].exports;var n=t[a]={i:a,l:!1,exports:{}};return e[a].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.m=e,r.c=t,r.d=function(e,t,a){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:a})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var a=Object.create(null);if(r.r(a),Object.defineProperty(a,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var n in e)r.d(a,n,function(t){return e[t]}.bind(null,n));return a},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="/",r(r.s=0)}({"./src/config/index.js":
/*!*****************************!*\
  !*** ./src/config/index.js ***!
  \*****************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;t.default={SITE:{NAME:"",CANONICAL:"",GA:""},BUSINESS:{NAME:"",ADDRESS:"",ADDRESS_2:"",CITY:"",POSTCODE:""},SOCIAL_MEDIA:{FACEBOOK:"",TWITTER:"",INSTAGRAM:""}}},"./src/site/Loading.js":
/*!*****************************!*\
  !*** ./src/site/Loading.js ***!
  \*****************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=function(){return a.default.createElement("h1",null,"A module is loading")};var a=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=n();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var o in e)if(Object.prototype.hasOwnProperty.call(e,o)){var s=a?Object.getOwnPropertyDescriptor(e,o):null;s&&(s.get||s.set)?Object.defineProperty(r,o,s):r[o]=e[o]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react"));function n(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return n=function(){return e},e}},"./src/site/auth/components/LoginButton/LoginButton.js":
/*!*************************************************************!*\
  !*** ./src/site/auth/components/LoginButton/LoginButton.js ***!
  \*************************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=i();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=(a=r(/*! prop-types */"prop-types"))&&a.__esModule?a:{default:a},s=r(/*! @fwrlines/ds */"@fwrlines/ds");function i(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return i=function(){return e},e}function l(){return(l=Object.assign||function(e){for(var t=1;t<arguments.length;t++){var r=arguments[t];for(var a in r)Object.prototype.hasOwnProperty.call(r,a)&&(e[a]=r[a])}return e}).apply(this,arguments)}const u=({providerName:e,dataKey:t,query:r,...a})=>n.createElement(s.OLoginButton,l({},a,{simple:!1,query:r,dataKey:t,providerName:e}));u.propTypes={label:o.default.string,query:o.default.string,dataKey:o.default.string},u.defaultProps={query:"query {\n  oAuth2Google\n}\n",dataKey:"oAuth2Google"};var c=u;t.default=c},"./src/site/auth/components/LoginButton/index.js":
/*!*******************************************************!*\
  !*** ./src/site/auth/components/LoginButton/index.js ***!
  \*******************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),Object.defineProperty(t,"LoginButton",{enumerable:!0,get:function(){return n.default}});var a,n=(a=r(/*! ./LoginButton */"./src/site/auth/components/LoginButton/LoginButton.js"))&&a.__esModule?a:{default:a}},"./src/site/auth/components/Redeemer/Redeemer.js":
/*!*******************************************************!*\
  !*** ./src/site/auth/components/Redeemer/Redeemer.js ***!
  \*******************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=u();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=r(/*! react-router-dom */"react-router-dom"),s=(a=r(/*! graphql-tag */"graphql-tag"))&&a.__esModule?a:{default:a},i=r(/*! @apollo/client */"@apollo/client"),l=r(/*! @fwrlines/ds */"@fwrlines/ds");function u(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return u=function(){return e},e}var c=e=>{const{code:t}=(0,o.useParams)(),r=(0,o.useHistory)(),[a,{data:{oAuth2Login:u}={},loading:c,error:d,called:p}]=(0,i.useMutation)((0,s.default)("mutation getJWT($code: String!) {\n  oAuth2Login(authorization_code: $code) {\n    access_token,\n    expires_in,\n    token_type\n  }\n}\n"),{variables:{code:t}});(0,n.useEffect)(()=>{!p&&t&&a()},[p,t,a]);const{setSessionCookie:f}=(0,n.useContext)(l.SessionContext);return(0,n.useEffect)(()=>{u&&(f(u.access_token,{maxAge:u.expires_in,secure:!("true"===(process&&process.env&&process.env.LOCAL||void 0))}),r.push("/"))},[r,f,u]),n.createElement(n.Fragment,null,n.createElement("h1",null,"We are redeeming a code to login"),n.createElement("pre",null,t))};t.default=c},"./src/site/auth/components/Redeemer/index.js":
/*!****************************************************!*\
  !*** ./src/site/auth/components/Redeemer/index.js ***!
  \****************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),Object.defineProperty(t,"Redeemer",{enumerable:!0,get:function(){return n.default}});var a,n=(a=r(/*! ./Redeemer */"./src/site/auth/components/Redeemer/Redeemer.js"))&&a.__esModule?a:{default:a}},"./src/site/auth/components/index.js":
/*!*******************************************!*\
  !*** ./src/site/auth/components/index.js ***!
  \*******************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),Object.defineProperty(t,"Redeemer",{enumerable:!0,get:function(){return a.Redeemer}}),Object.defineProperty(t,"LoginButton",{enumerable:!0,get:function(){return n.LoginButton}});var a=r(/*! ./Redeemer */"./src/site/auth/components/Redeemer/index.js"),n=r(/*! ./LoginButton */"./src/site/auth/components/LoginButton/index.js")},"./src/site/auth/index.js":
/*!********************************!*\
  !*** ./src/site/auth/index.js ***!
  \********************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),Object.defineProperty(t,"routes",{enumerable:!0,get:function(){return a.default}}),Object.defineProperty(t,"URLS",{enumerable:!0,get:function(){return n.default}});var a=o(r(/*! ./routes */"./src/site/auth/routes.js")),n=o(r(/*! ./urls */"./src/site/auth/urls.js"));function o(e){return e&&e.__esModule?e:{default:e}}},"./src/site/auth/pages/Login.js":
/*!**************************************!*\
  !*** ./src/site/auth/pages/Login.js ***!
  \**************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=d();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),n=c(r(/*! prop-types */"prop-types")),o=r(/*! @fwrlines/ds */"@fwrlines/ds"),s=r(/*! ../components */"./src/site/auth/components/index.js"),i=r(/*! react-router-dom */"react-router-dom"),l=r(/*! react-intl */"react-intl"),u=c(r(/*! ./messages */"./src/site/auth/pages/messages.js"));function c(e){return e&&e.__esModule?e:{default:e}}function d(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return d=function(){return e},e}const p={subtitle:a.createElement(l.FormattedMessage,u.default.loginSubtitle),heading:a.createElement(l.FormattedMessage,u.default.loginTitle),headingAs:"h1"},f=({})=>{const{isConnected:e,dashboardHomePath:t}=(0,a.useContext)(o.SessionContext),r=(0,i.useHistory)();return(0,a.useEffect)(()=>{e&&r.push(t)},[r,t,e]),a.createElement(o.Page,{id:"page_login"},a.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},a.createElement(o.Heading,p)),a.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},a.createElement(s.LoginButton,null)))};f.propTypes={someprop:n.default.node};var h=f;t.default=h},"./src/site/auth/pages/Unauthorized.js":
/*!*********************************************!*\
  !*** ./src/site/auth/pages/Unauthorized.js ***!
  \*********************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=u();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),n=l(r(/*! prop-types */"prop-types")),o=r(/*! @fwrlines/ds */"@fwrlines/ds"),s=r(/*! react-intl */"react-intl"),i=l(r(/*! ./messages */"./src/site/auth/pages/messages.js"));function l(e){return e&&e.__esModule?e:{default:e}}function u(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return u=function(){return e},e}const c={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},d={subtitle:a.createElement(s.FormattedMessage,i.default.unauthorizedSubtitle),heading:a.createElement(s.FormattedMessage,i.default.unauthorizedTitle),headingAs:"h1",label:"Error",labelClassName:"x-red basic"},p=({})=>a.createElement(o.Page,{id:"page_unauthorized",itemType:"https://schema.org/FAQPage",HELMET:c},a.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},a.createElement(o.Heading,d)),a.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},a.createElement("p",null,a.createElement(s.FormattedMessage,i.default.unauthorizedExplanation)," ",a.createElement(o.SupportEmailLink,{label:a.createElement(s.FormattedMessage,i.default.unauthorizedContact)}))));p.propTypes={someprop:n.default.node};var f=p;t.default=f},"./src/site/auth/pages/messages.js":
/*!*****************************************!*\
  !*** ./src/site/auth/pages/messages.js ***!
  \*****************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a=(0,r(/*! react-intl */"react-intl").defineMessages)({loginTitle:{id:"app.auth.pages.login.title",defaultMessage:"Dashboard Access"},loginSubtitle:{id:"app.auth.pages.login.subtitle",defaultMessage:"Login below to your dashboard account"},unauthorizedTitle:{id:"app.auth.pages.unauthorized.title",defaultMessage:"Unauthorized"},unauthorizedSubtitle:{id:"app.auth.pages.unauthorized.subtitle",defaultMessage:"Your have sucessfully connected your account, but you are not allowed to log in."},unauthorizedExplanation:{id:"app.auth.pages.unauthorized.explanation",defaultMessage:"You can try to login with another account. Alternatively, if you believe this is a mistake"},unauthorizedContact:{id:"app.auth.pages.unauthorized.contact",defaultMessage:"you can contact support here."}});t.default=a},"./src/site/auth/routes.js":
/*!*********************************!*\
  !*** ./src/site/auth/routes.js ***!
  \*********************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a=r(/*! ../../utils */"./src/utils/index.js"),n=s(r(/*! ./urls */"./src/site/auth/urls.js")),o=r(/*! @fwrlines/ds */"@fwrlines/ds");function s(e){return e&&e.__esModule?e:{default:e}}function i(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return i=function(){return e},e}function l(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=i();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}return r.default=e,t&&t.set(e,r),r}const u="app.auth",c=":code([0-9a-z-]{64})";var d=[{path:(0,a.urljoin)(n.default.REDEEM,c),component:(0,a.loadable)({resolved:{},chunkName:()=>"app.auth",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>l(r(/*! ./components/Redeemer/Redeemer.js */"./src/site/auth/components/Redeemer/Redeemer.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./components/Redeemer/Redeemer.js */
return"./src/site/auth/components/Redeemer/Redeemer.js"}})},{path:n.default.LOGIN,component:(0,a.loadable)({resolved:{},chunkName:()=>"app.auth",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>l(r(/*! ./pages/Login.js */"./src/site/auth/pages/Login.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/Login.js */
return"./src/site/auth/pages/Login.js"}})},{path:n.default.LOGOUT,component:o.Logout,isPrivate:!0},{path:n.default.UNAUTHORIZED,component:(0,a.loadable)({resolved:{},chunkName:()=>"app.auth",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>l(r(/*! ./pages/Unauthorized.js */"./src/site/auth/pages/Unauthorized.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/Unauthorized.js */
return"./src/site/auth/pages/Unauthorized.js"}})}];t.default=d},"./src/site/auth/urls.js":
/*!*******************************!*\
  !*** ./src/site/auth/urls.js ***!
  \*******************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;r(/*! ../../utils */"./src/utils/index.js");t.default={LOGIN:"/login",REDEEM:"/redeem",LOGOUT:"/logout",UNAUTHORIZED:"/unauthorized"}},"./src/site/dashboard/components/MyProfile.js":
/*!****************************************************!*\
  !*** ./src/site/dashboard/components/MyProfile.js ***!
  \****************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=o();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var s=a?Object.getOwnPropertyDescriptor(e,n):null;s&&(s.get||s.set)?Object.defineProperty(r,n,s):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),n=r(/*! @fwrlines/ds */"@fwrlines/ds");r(/*! react-router-dom */"react-router-dom");function o(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return o=function(){return e},e}var s=({})=>{const{currentUserData:e={},currentUserLoading:t}=(0,a.useContext)(n.SessionContext);console.log("EXE => Consumer, context is",e);const r=e.oAuth2Profiles?e.oAuth2Profiles.find(e=>"google"==e.provider):{};return a.createElement(a.Fragment,null,e?a.createElement(a.Fragment,null,a.createElement(n.CircleInfo,{title:r.name,subtitle:r.email,className:"s3 k-s",image:r.picture,imageAlt:r.name})):"You are not connected")};t.default=s},"./src/site/dashboard/components/ThemeSelector/ThemeSelector.js":
/*!**********************************************************************!*\
  !*** ./src/site/dashboard/components/ThemeSelector/ThemeSelector.js ***!
  \**********************************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a=c(r(/*! react */"react")),n=l(r(/*! prop-types */"prop-types")),o=r(/*! @fwrlines/ds */"@fwrlines/ds"),s=r(/*! react-intl */"react-intl"),i=l(r(/*! ./messages */"./src/site/dashboard/components/ThemeSelector/messages.js"));l(r(/*! ./theme_selector.scss */"./src/site/dashboard/components/ThemeSelector/theme_selector.scss"));function l(e){return e&&e.__esModule?e:{default:e}}function u(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return u=function(){return e},e}function c(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=u();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}return r.default=e,t&&t.set(e,r),r}r(/*! ../../../../utils/isBackend */"./src/utils/isBackend.js").isBackend||(console.log("This is not backend"),Promise.resolve().then(()=>c(r(/*! ./theme_selector.scss */"./src/site/dashboard/components/ThemeSelector/theme_selector.scss"))));const d="theme_selector",p=[{value:"light",id:"light",label:a.createElement(s.FormattedMessage,i.default.lightTheme)},{value:"dark",id:"dark",label:a.createElement(s.FormattedMessage,i.default.darkTheme)},{value:"iceberg",id:"iceberg",label:"Iceberg"},{value:"system",id:"sys",label:a.createElement(s.FormattedMessage,i.default.systemTheme)}],f=({id:e,className:t,style:r})=>{const{preferredTheme:n,setPreferredTheme:l}=(0,a.useContext)(o.SiteContext);return a.createElement("span",{className:[d,"x-metadata c-x",t].filter(e=>e).join(" "),id:e,style:r},a.createElement("span",null,a.createElement(s.FormattedMessage,i.default.theme)," ",":"),a.createElement(o.DownshiftSelect,{inputId:"dashboard-theme-selector",options:p,aesthetic:"mars",setInputValue:l,value:n,style:{display:"inline-block",width:"auto"},buttonProps:{className:"x-subtitle",simple:!0,icon:"j",iconSide:"r"}}))};f.propTypes={id:n.default.string,className:n.default.string,style:n.default.object,children:n.default.node,as:n.default.oneOfType([n.default.string,n.default.object]),height:n.default.string,width:n.default.string};var h=f;t.default=h},"./src/site/dashboard/components/ThemeSelector/index.js":
/*!**************************************************************!*\
  !*** ./src/site/dashboard/components/ThemeSelector/index.js ***!
  \**************************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),Object.defineProperty(t,"ThemeSelector",{enumerable:!0,get:function(){return n.default}});var a,n=(a=r(/*! ./ThemeSelector */"./src/site/dashboard/components/ThemeSelector/ThemeSelector.js"))&&a.__esModule?a:{default:a}},"./src/site/dashboard/components/ThemeSelector/messages.js":
/*!*****************************************************************!*\
  !*** ./src/site/dashboard/components/ThemeSelector/messages.js ***!
  \*****************************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a=(0,r(/*! react-intl */"react-intl").defineMessages)({lightTheme:{id:"app.dashboard.theme_selector.light_theme",defaultMessage:"Light"},darkTheme:{id:"app.dashboard.theme_selector.dark_theme",defaultMessage:"Dark"},systemTheme:{id:"app.dashboard.theme_selector.system_theme",defaultMessage:"System"},theme:{id:"app.dashboard.theme_selector.theme",defaultMessage:"Theme"}});t.default=a},"./src/site/dashboard/components/ThemeSelector/theme_selector.scss":
/*!*************************************************************************!*\
  !*** ./src/site/dashboard/components/ThemeSelector/theme_selector.scss ***!
  \*************************************************************************/
/*! no static exports found */function(e,t){},"./src/site/dashboard/components/index.js":
/*!************************************************!*\
  !*** ./src/site/dashboard/components/index.js ***!
  \************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),Object.defineProperty(t,"MyProfile",{enumerable:!0,get:function(){return n.default}}),Object.defineProperty(t,"ThemeSelector",{enumerable:!0,get:function(){return o.ThemeSelector}});var a,n=(a=r(/*! ./MyProfile */"./src/site/dashboard/components/MyProfile.js"))&&a.__esModule?a:{default:a},o=r(/*! ./ThemeSelector */"./src/site/dashboard/components/ThemeSelector/index.js")},"./src/site/dashboard/index.js":
/*!*************************************!*\
  !*** ./src/site/dashboard/index.js ***!
  \*************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),Object.defineProperty(t,"routes",{enumerable:!0,get:function(){return a.default}}),Object.defineProperty(t,"URLS",{enumerable:!0,get:function(){return n.default}});var a=o(r(/*! ./routes */"./src/site/dashboard/routes.js")),n=o(r(/*! ./urls */"./src/site/dashboard/urls.js"));function o(e){return e&&e.__esModule?e:{default:e}}},"./src/site/dashboard/layouts/Main.js":
/*!********************************************!*\
  !*** ./src/site/dashboard/layouts/Main.js ***!
  \********************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=l();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=(a=r(/*! prop-types */"prop-types"))&&a.__esModule?a:{default:a},s=r(/*! @fwrlines/ds */"@fwrlines/ds"),i=r(/*! ../components */"./src/site/dashboard/components/index.js");function l(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return l=function(){return e},e}const u=({routes:e,navTree:t,...r})=>{const{userTheme:a}=(0,n.useContext)(s.SiteContext);return n.createElement(s.DashboardContextProvider,null,n.createElement(s.DashboardNavigation,{tree:t,footer:n.createElement(i.ThemeSelector,null)}),n.createElement(s.DashboardMain,null,n.createElement(s.DashboardNavigation.HorizontalBar,{className:"md-h lg-h u50",label:"blah"}),n.createElement(s.SwitchRouteMap,{routes:e,NotFound:n.createElement("div",{style:{height:"120vh"}},"Content Goes here")})))};u.propTypes={routes:o.default.arrayOf(o.default.object),navTree:o.default.object};var c=u;t.default=c},"./src/site/dashboard/layouts/index.js":
/*!*********************************************!*\
  !*** ./src/site/dashboard/layouts/index.js ***!
  \*********************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),Object.defineProperty(t,"MainLayout",{enumerable:!0,get:function(){return n.default}});var a,n=(a=r(/*! ./Main */"./src/site/dashboard/layouts/Main.js"))&&a.__esModule?a:{default:a}},"./src/site/dashboard/navigation/index.js":
/*!************************************************!*\
  !*** ./src/site/dashboard/navigation/index.js ***!
  \************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),Object.defineProperty(t,"messages",{enumerable:!0,get:function(){return a.default}}),Object.defineProperty(t,"tree",{enumerable:!0,get:function(){return n.default}});var a=o(r(/*! ./messages */"./src/site/dashboard/navigation/messages.js")),n=o(r(/*! ./tree */"./src/site/dashboard/navigation/tree.js"));function o(e){return e&&e.__esModule?e:{default:e}}},"./src/site/dashboard/navigation/messages.js":
/*!***************************************************!*\
  !*** ./src/site/dashboard/navigation/messages.js ***!
  \***************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a=(0,r(/*! react-intl */"react-intl").defineMessages)({home:{id:"app.dashboard.navtree.home",defaultMessage:"Home"},account:{id:"app.dashboard.navtree.account",defaultMessage:"Account Information"},account_home:{id:"app.dashboard.navtree.account_home",defaultMessage:"Overview"},account_label:{id:"app.dashboard.navtree.account_label",defaultMessage:"Account"},account_google_integration:{id:"app.dashboard.navtree.account_google_integration",defaultMessage:"Google Account Link"},account_profile:{id:"app.dashboard.navtree.account_profile",defaultMessage:"My Profile"},billing:{id:"app.dashboard.navtree.billing",defaultMessage:"Plan and payment"},billing_home:{id:"app.dashboard.navtree.billing_home",defaultMessage:"General"},billing_payment:{id:"app.dashboard.navtree.billing_payment",defaultMessage:"Payment details"},billing_plan:{id:"app.dashboard.navtree.billing_plan",defaultMessage:"Plan details"},logout:{id:"app.dashboard.navtree.logout",defaultMessage:"Logout"},shop:{id:"app.dashboard.navtree.shop",defaultMessage:"My Shop"},shop_home:{id:"app.dashboard.navtree.shop_home",defaultMessage:"General"},shop_contact:{id:"app.dashboard.navtree.shop_contact",defaultMessage:"Public Information"},shop_hours:{id:"app.dashboard.navtree.shop_hours",defaultMessage:"Opening Hours"},website:{id:"app.dashboard.navtree.website",defaultMessage:"My Website"},website_pages:{id:"app.dashboard.navtree.website_pages",defaultMessage:"Pages"}});t.default=a},"./src/site/dashboard/navigation/tree.js":
/*!***********************************************!*\
  !*** ./src/site/dashboard/navigation/tree.js ***!
  \***********************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=u();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),n=l(r(/*! ../urls */"./src/site/dashboard/urls.js")),o=r(/*! ../../urls */"./src/site/urls.js"),s=r(/*! react-intl */"react-intl"),i=l(r(/*! ./messages */"./src/site/dashboard/navigation/messages.js"));function l(e){return e&&e.__esModule?e:{default:e}}function u(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return u=function(){return e},e}var c={title:"WebOffice",pathname:n.default.HOME,subItems:[{title:a.createElement(s.FormattedMessage,i.default.home),pathname:n.default.HOME},{section:"WebOfficina",title:a.createElement(s.FormattedMessage,i.default.website),pathname:n.default.WEBSITE_HOME},{section:"WebOfficina",title:a.createElement(s.FormattedMessage,i.default.shop),pathname:n.default.SHOP_HOME,subItems:[{title:a.createElement(s.FormattedMessage,i.default.shop_hours),pathname:n.default.SHOP_HOURS},{title:a.createElement(s.FormattedMessage,i.default.shop_contact),pathname:n.default.SHOP_CONTACT}]},{section:a.createElement(s.FormattedMessage,i.default.account_label),title:a.createElement(s.FormattedMessage,i.default.account),pathname:n.default.ACCOUNT_HOME,logo:"/illustrations/iso-computer.png",subItems:[{title:a.createElement(s.FormattedMessage,i.default.account_home),pathname:n.default.ACCOUNT_HOME},{title:a.createElement(s.FormattedMessage,i.default.account_profile),pathname:n.default.ACCOUNT_PROFILE},{title:a.createElement(s.FormattedMessage,i.default.account_google_integration),pathname:n.default.ACCOUNT_GOOGLE_INTEGRATION}]},{section:a.createElement(s.FormattedMessage,i.default.account_label),title:a.createElement(s.FormattedMessage,i.default.billing),pathname:n.default.PLAN_HOME,subItems:[{title:a.createElement(s.FormattedMessage,i.default.billing_home),pathname:n.default.PLAN_HOME},{title:a.createElement(s.FormattedMessage,i.default.billing_plan),pathname:n.default.PLAN_DETAILS},{title:a.createElement(s.FormattedMessage,i.default.billing_payment),pathname:n.default.PLAN_PAYMENT}]},{section:a.createElement(s.FormattedMessage,i.default.account_label),title:a.createElement(s.FormattedMessage,i.default.logout),pathname:o.AUTH.LOGOUT}]};t.default=c},"./src/site/dashboard/pages/AccountGoogleIntegration.js":
/*!**************************************************************!*\
  !*** ./src/site/dashboard/pages/AccountGoogleIntegration.js ***!
  \**************************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=i();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=(a=r(/*! prop-types */"prop-types"))&&a.__esModule?a:{default:a},s=r(/*! @fwrlines/ds */"@fwrlines/ds");function i(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return i=function(){return e},e}const l={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},u={subtitle:"A place to edit data",heading:"Google Integration",headingAs:"h1"},c=({history:e,location:t,match:r})=>n.createElement(s.Page,{id:"page_account_google_integration",itemType:"https://schema.org/FAQPage",HELMET:l},n.createElement(s.Page.Section,{head:!0,className:"p-u u2",id:"head"},n.createElement(s.Heading,u)),n.createElement(s.Page.Section,{id:"a1",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")),n.createElement(s.Page.Section,{id:"a2",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")));c.propTypes={someprop:o.default.node};var d=c;t.default=d},"./src/site/dashboard/pages/AccountHome.js":
/*!*************************************************!*\
  !*** ./src/site/dashboard/pages/AccountHome.js ***!
  \*************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=i();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=(a=r(/*! prop-types */"prop-types"))&&a.__esModule?a:{default:a},s=r(/*! @fwrlines/ds */"@fwrlines/ds");function i(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return i=function(){return e},e}const l={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},u={subtitle:"A place to edit data",heading:"Account : general",headingAs:"h1"},c=({history:e,location:t,match:r})=>n.createElement(s.Page,{id:"page_account_home",itemType:"https://schema.org/FAQPage",HELMET:l},n.createElement(s.Page.Section,{head:!0,className:"p-u u2",id:"head"},n.createElement(s.Heading,u)),n.createElement(s.Page.Section,{id:"a1",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")),n.createElement(s.Page.Section,{id:"a2",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")));c.propTypes={someprop:o.default.node};var d=c;t.default=d},"./src/site/dashboard/pages/Home.js":
/*!******************************************!*\
  !*** ./src/site/dashboard/pages/Home.js ***!
  \******************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=i();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=(a=r(/*! prop-types */"prop-types"))&&a.__esModule?a:{default:a},s=r(/*! @fwrlines/ds */"@fwrlines/ds");function i(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return i=function(){return e},e}const l={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},u={subtitle:"A place to edit data",heading:"Home",headingAs:"h1"},c=({history:e,location:t,match:r})=>n.createElement(s.Page,{id:"page_home",itemType:"https://schema.org/FAQPage",HELMET:l},n.createElement(s.Page.Section,{head:!0,className:"p-u u2",id:"head"},n.createElement(s.Heading,u)),n.createElement(s.Page.Section,{id:"a1",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")),n.createElement(s.Page.Section,{id:"a2",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")));c.propTypes={someprop:o.default.node};var d=c;t.default=d},"./src/site/dashboard/pages/PlanDetails.js":
/*!*************************************************!*\
  !*** ./src/site/dashboard/pages/PlanDetails.js ***!
  \*************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=i();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=(a=r(/*! prop-types */"prop-types"))&&a.__esModule?a:{default:a},s=r(/*! @fwrlines/ds */"@fwrlines/ds");function i(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return i=function(){return e},e}const l={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},u={subtitle:"A place to edit data",heading:"Shop Details",headingAs:"h1"},c=({history:e,location:t,match:r})=>n.createElement(s.Page,{id:"page_account_plan_details",itemType:"https://schema.org/FAQPage",HELMET:l},n.createElement(s.Page.Section,{head:!0,className:"p-u u2",id:"head"},n.createElement(s.Heading,u)),n.createElement(s.Page.Section,{id:"a1",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")),n.createElement(s.Page.Section,{id:"a2",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")));c.propTypes={someprop:o.default.node};var d=c;t.default=d},"./src/site/dashboard/pages/PlanHome.js":
/*!**********************************************!*\
  !*** ./src/site/dashboard/pages/PlanHome.js ***!
  \**********************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=i();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=(a=r(/*! prop-types */"prop-types"))&&a.__esModule?a:{default:a},s=r(/*! @fwrlines/ds */"@fwrlines/ds");function i(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return i=function(){return e},e}const l={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},u={subtitle:"A place to edit data",heading:"Plan Home",headingAs:"h1"},c=({history:e,location:t,match:r})=>n.createElement(s.Page,{id:"page_account_plan_home",itemType:"https://schema.org/FAQPage",HELMET:l},n.createElement(s.Page.Section,{head:!0,className:"p-u u2",id:"head"},n.createElement(s.Heading,u)),n.createElement(s.Page.Section,{id:"a1",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")),n.createElement(s.Page.Section,{id:"a2",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")));c.propTypes={someprop:o.default.node};var d=c;t.default=d},"./src/site/dashboard/pages/PlanPayment.js":
/*!*************************************************!*\
  !*** ./src/site/dashboard/pages/PlanPayment.js ***!
  \*************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=i();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=(a=r(/*! prop-types */"prop-types"))&&a.__esModule?a:{default:a},s=r(/*! @fwrlines/ds */"@fwrlines/ds");function i(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return i=function(){return e},e}const l={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},u={subtitle:"A place to edit data",heading:"Plan Payment",headingAs:"h1"},c=({history:e,location:t,match:r})=>n.createElement(s.Page,{id:"page_account_plan_payment",itemType:"https://schema.org/FAQPage",HELMET:l},n.createElement(s.Page.Section,{head:!0,className:"p-u u2",id:"head"},n.createElement(s.Heading,u)),n.createElement(s.Page.Section,{id:"a1",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")),n.createElement(s.Page.Section,{id:"a2",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")));c.propTypes={someprop:o.default.node};var d=c;t.default=d},"./src/site/dashboard/pages/Profile.js":
/*!*********************************************!*\
  !*** ./src/site/dashboard/pages/Profile.js ***!
  \*********************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=l();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=(a=r(/*! prop-types */"prop-types"))&&a.__esModule?a:{default:a},s=r(/*! @fwrlines/ds */"@fwrlines/ds"),i=r(/*! ../components */"./src/site/dashboard/components/index.js");function l(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return l=function(){return e},e}const u={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},c={subtitle:"In this page you can view and modify information related to your profile on this website.",heading:"My Profile",headingClassName:"ts-green",headingAs:"h1"},d=({history:e,location:t,match:r})=>n.createElement(s.Page,{id:"page_profile",itemType:"https://schema.org/FAQPage",HELMET:u},n.createElement(s.Page.Section,{head:!0,className:"p-u u2",id:"head"},n.createElement(s.Heading,c)),n.createElement(s.Page.Section,{id:"a1",className:"p-u u2"},n.createElement(i.MyProfile,null)),n.createElement(s.Page.Section,{id:"a2",className:"p-u u2"},n.createElement("p",null,"Here a form to edit your data")));d.propTypes={someprop:o.default.node};var p=d;t.default=p},"./src/site/dashboard/pages/ShopContact.js":
/*!*************************************************!*\
  !*** ./src/site/dashboard/pages/ShopContact.js ***!
  \*************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=i();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=(a=r(/*! prop-types */"prop-types"))&&a.__esModule?a:{default:a},s=r(/*! @fwrlines/ds */"@fwrlines/ds");function i(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return i=function(){return e},e}const l={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},u={className:"uc",subtitle:"Stanley Kubrick, 1960",heading:"Spartacus",headingClassName:"ts-green",headingAs:"h1",label:"Film",labelClassName:"x-red basic"},c=({history:e,location:t,match:r})=>n.createElement(s.Page,{id:"page_shop_contact",itemType:"https://schema.org/FAQPage",HELMET:l},n.createElement(s.Page.Section,{head:!0,className:"p-u u2",id:"head"},n.createElement(s.Heading,u)),n.createElement(s.Page.Section,{id:"a1",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")),n.createElement(s.Page.Section,{id:"a2",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")));c.propTypes={someprop:o.default.node};var d=c;t.default=d},"./src/site/dashboard/pages/ShopDetails.js":
/*!*************************************************!*\
  !*** ./src/site/dashboard/pages/ShopDetails.js ***!
  \*************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=i();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=(a=r(/*! prop-types */"prop-types"))&&a.__esModule?a:{default:a},s=r(/*! @fwrlines/ds */"@fwrlines/ds");function i(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return i=function(){return e},e}const l={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},u={subtitle:"A place to edit data",heading:"Shop Details",headingAs:"h1"},c=({history:e,location:t,match:r})=>n.createElement(s.Page,{id:"page_shop_details",itemType:"https://schema.org/FAQPage",HELMET:l},n.createElement(s.Page.Section,{head:!0,className:"p-u u2",id:"head"},n.createElement(s.Heading,u)),n.createElement(s.Page.Section,{id:"a1",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")),n.createElement(s.Page.Section,{id:"a2",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")));c.propTypes={someprop:o.default.node};var d=c;t.default=d},"./src/site/dashboard/pages/ShopHome.js":
/*!**********************************************!*\
  !*** ./src/site/dashboard/pages/ShopHome.js ***!
  \**********************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=i();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=(a=r(/*! prop-types */"prop-types"))&&a.__esModule?a:{default:a},s=r(/*! @fwrlines/ds */"@fwrlines/ds");function i(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return i=function(){return e},e}const l={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},u={subtitle:"A place to edit data",heading:"Shop Home",headingAs:"h1"},c=({history:e,location:t,match:r})=>n.createElement(s.Page,{id:"page_shop_home",itemType:"https://schema.org/FAQPage",HELMET:l},n.createElement(s.Page.Section,{head:!0,className:"p-u u2",id:"head"},n.createElement(s.Heading,u)),n.createElement(s.Page.Section,{id:"a1",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")),n.createElement(s.Page.Section,{id:"a2",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")));c.propTypes={someprop:o.default.node};var d=c;t.default=d},"./src/site/dashboard/pages/ShopHours.js":
/*!***********************************************!*\
  !*** ./src/site/dashboard/pages/ShopHours.js ***!
  \***********************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=i();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=(a=r(/*! prop-types */"prop-types"))&&a.__esModule?a:{default:a},s=r(/*! @fwrlines/ds */"@fwrlines/ds");function i(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return i=function(){return e},e}const l={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},u={className:"uc",subtitle:"Stanley Kubrick, 1960",heading:"Spartacus",headingClassName:"ts-green",headingAs:"h1",label:"Film",labelClassName:"x-red basic"},c=({history:e,location:t,match:r})=>n.createElement(s.Page,{id:"page_shop_hours",itemType:"https://schema.org/FAQPage",HELMET:l},n.createElement(s.Page.Section,{head:!0,className:"p-u u2",id:"head"},n.createElement(s.Heading,u)),n.createElement(s.Page.Section,{id:"a1",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")),n.createElement(s.Page.Section,{id:"a2",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")));c.propTypes={someprop:o.default.node};var d=c;t.default=d},"./src/site/dashboard/pages/WebsiteHome.js":
/*!*************************************************!*\
  !*** ./src/site/dashboard/pages/WebsiteHome.js ***!
  \*************************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=i();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! react */"react")),o=(a=r(/*! prop-types */"prop-types"))&&a.__esModule?a:{default:a},s=r(/*! @fwrlines/ds */"@fwrlines/ds");function i(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return i=function(){return e},e}const l={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},u={subtitle:"A place to edit data",heading:"Website Home",headingAs:"h1"},c=({history:e,location:t,match:r})=>n.createElement(s.Page,{id:"page_website_home",itemType:"https://schema.org/FAQPage",HELMET:l},n.createElement(s.Page.Section,{head:!0,className:"p-u u2",id:"head"},n.createElement(s.Heading,u)),n.createElement(s.Page.Section,{id:"a1",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")),n.createElement(s.Page.Section,{id:"a2",className:"p-u u2"},n.createElement("h2",null,"Section A2"),n.createElement("p",null,"Some content here. Blah blah")));c.propTypes={someprop:o.default.node};var d=c;t.default=d},"./src/site/dashboard/routes.js":
/*!**************************************!*\
  !*** ./src/site/dashboard/routes.js ***!
  \**************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a=d(r(/*! react */"react")),n=r(/*! ../../utils */"./src/utils/index.js"),o=r(/*! ./layouts */"./src/site/dashboard/layouts/index.js"),s=r(/*! ./navigation */"./src/site/dashboard/navigation/index.js"),i=l(r(/*! ./urls */"./src/site/dashboard/urls.js"));function l(e){return e&&e.__esModule?e:{default:e}}function u(){return(u=Object.assign||function(e){for(var t=1;t<arguments.length;t++){var r=arguments[t];for(var a in r)Object.prototype.hasOwnProperty.call(r,a)&&(e[a]=r[a])}return e}).apply(this,arguments)}function c(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return c=function(){return e},e}function d(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=c();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}return r.default=e,t&&t.set(e,r),r}const p="app.dashboard",f=[{path:i.default.HOME,component:(0,n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>d(r(/*! ./pages/Home.js */"./src/site/dashboard/pages/Home.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/Home.js */
return"./src/site/dashboard/pages/Home.js"}}),exact:!0,isPrivate:!0},{path:i.default.PROFILE,component:(0,n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>d(r(/*! ./pages/Profile.js */"./src/site/dashboard/pages/Profile.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/Profile.js */
return"./src/site/dashboard/pages/Profile.js"}}),exact:!0,isPrivate:!0},{path:i.default.WEBSITE_HOME,component:(0,n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>d(r(/*! ./pages/WebsiteHome.js */"./src/site/dashboard/pages/WebsiteHome.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/WebsiteHome.js */
return"./src/site/dashboard/pages/WebsiteHome.js"}}),exact:!0,isPrivate:!0},{path:i.default.SHOP_HOME,component:(0,n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>d(r(/*! ./pages/ShopHome.js */"./src/site/dashboard/pages/ShopHome.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/ShopHome.js */
return"./src/site/dashboard/pages/ShopHome.js"}}),exact:!0,isPrivate:!0},{path:i.default.SHOP_DETAILS,component:(0,n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>d(r(/*! ./pages/ShopDetails.js */"./src/site/dashboard/pages/ShopDetails.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/ShopDetails.js */
return"./src/site/dashboard/pages/ShopDetails.js"}}),exact:!0,isPrivate:!0},{path:i.default.SHOP_HOURS,component:(0,n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>d(r(/*! ./pages/ShopHours.js */"./src/site/dashboard/pages/ShopHours.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/ShopHours.js */
return"./src/site/dashboard/pages/ShopHours.js"}}),exact:!0,isPrivate:!0},{path:i.default.SHOP_CONTACT,component:(0,n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>d(r(/*! ./pages/ShopContact.js */"./src/site/dashboard/pages/ShopContact.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/ShopContact.js */
return"./src/site/dashboard/pages/ShopContact.js"}}),exact:!0,isPrivate:!0},{path:i.default.ACCOUNT_HOME,component:(0,n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>d(r(/*! ./pages/AccountHome.js */"./src/site/dashboard/pages/AccountHome.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/AccountHome.js */
return"./src/site/dashboard/pages/AccountHome.js"}}),exact:!0,isPrivate:!0},{path:i.default.ACCOUNT_PROFILE,component:(0,n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>d(r(/*! ./pages/Profile.js */"./src/site/dashboard/pages/Profile.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/Profile.js */
return"./src/site/dashboard/pages/Profile.js"}}),exact:!0,isPrivate:!0},{path:i.default.ACCOUNT_GOOGLE_INTEGRATION,component:(0,n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>d(r(/*! ./pages/AccountGoogleIntegration.js */"./src/site/dashboard/pages/AccountGoogleIntegration.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/AccountGoogleIntegration.js */
return"./src/site/dashboard/pages/AccountGoogleIntegration.js"}}),exact:!0,isPrivate:!0},{path:i.default.PLAN_HOME,component:(0,n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>d(r(/*! ./pages/PlanHome.js */"./src/site/dashboard/pages/PlanHome.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/PlanHome.js */
return"./src/site/dashboard/pages/PlanHome.js"}}),exact:!0,isPrivate:!0},{path:i.default.PLAN_DETAILS,component:(0,n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>d(r(/*! ./pages/PlanDetails.js */"./src/site/dashboard/pages/PlanDetails.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/PlanDetails.js */
return"./src/site/dashboard/pages/PlanDetails.js"}}),exact:!0,isPrivate:!0},{path:i.default.PLAN_PAYMENT,component:(0,n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){const t=this.resolve(e);return!1!==this.resolved[t]&&!!r.m[t]},importAsync:()=>Promise.resolve().then(()=>d(r(/*! ./pages/PlanPayment.js */"./src/site/dashboard/pages/PlanPayment.js"))),requireAsync(e){const t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){const t=this.resolve(e);return r(t)},resolve(){/*! ./pages/PlanPayment.js */
return"./src/site/dashboard/pages/PlanPayment.js"}}),exact:!0,isPrivate:!0}];var h=[{path:i.default.all,render:e=>a.createElement(o.MainLayout,u({routes:f,navTree:s.tree},e))}];t.default=h},"./src/site/dashboard/urls.js":
/*!************************************!*\
  !*** ./src/site/dashboard/urls.js ***!
  \************************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a=r(/*! ../../utils */"./src/utils/index.js");var n={basePath:"/d/",all:(0,a.urljoin)("/d/","*"),HOME:"/d/",WEBSITE_HOME:(0,a.urljoin)("/d/","/website/"),SHOP_HOME:(0,a.urljoin)("/d/","/shop/"),SHOP_DETAILS:(0,a.urljoin)("/d/","/shop/","details"),SHOP_HOURS:(0,a.urljoin)("/d/","/shop/","opening-hours"),SHOP_CONTACT:(0,a.urljoin)("/d/","/shop/","contact"),ACCOUNT_HOME:(0,a.urljoin)("/d/","/account/"),ACCOUNT_PROFILE:(0,a.urljoin)("/d/","/account/","profile"),ACCOUNT_GOOGLE_INTEGRATION:(0,a.urljoin)("/d/","/account/","google"),PLAN_HOME:(0,a.urljoin)("/d/","/plan/"),PLAN_DETAILS:(0,a.urljoin)("/d/","/plan/","details"),PLAN_PAYMENT:(0,a.urljoin)("/d/","/plan/","billing"),PROFILE:(0,a.urljoin)("/d/","profile"),PROFILE2:(0,a.urljoin)("/d/","profile2")};t.default=n},"./src/site/urls.js":
/*!**************************!*\
  !*** ./src/site/urls.js ***!
  \**************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),Object.defineProperty(t,"DASHBOARD",{enumerable:!0,get:function(){return a.URLS}}),Object.defineProperty(t,"AUTH",{enumerable:!0,get:function(){return n.URLS}}),t.STATIC=void 0;var a=r(/*! ./dashboard */"./src/site/dashboard/index.js"),n=r(/*! ./auth */"./src/site/auth/index.js");t.STATIC={HOME:"",ANOTHERPAGE:"longer/url/for/sitemap"}},"./src/sitemap/renderer.js":
/*!*********************************!*\
  !*** ./src/sitemap/renderer.js ***!
  \*********************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a,n=(a=r(/*! ../config */"./src/config/index.js"))&&a.__esModule?a:{default:a},o=function(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=l();if(t&&t.has(e))return t.get(e);var r={},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var n in e)if(Object.prototype.hasOwnProperty.call(e,n)){var o=a?Object.getOwnPropertyDescriptor(e,n):null;o&&(o.get||o.set)?Object.defineProperty(r,n,o):r[n]=e[n]}r.default=e,t&&t.set(e,r);return r}(r(/*! ../site/urls */"./src/site/urls.js")),s=r(/*! date-fns */"date-fns"),i=r(/*! ../utils */"./src/utils/index.js");function l(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return l=function(){return e},e}const u={HOME:{changefreq:"yearly",priority:.5,lastmod:new Date("2019-10-02")},ANOTHERPAGE:{changefreq:"daily",priority:.5,lastmod:new Date("2019-09-12")}};t.default=async(e,t)=>{new Date;const r=[];return Object.keys(o.STATIC).forEach(e=>{const{changefreq:t,priority:a,lastmod:n}=u[e],s=o.STATIC[e];r.push({loc:s,lastmod:n,changefreq:t,priority:a})}),t.setHeader("Content-Type","text/xml"),t.send('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n</urlset> \n'.replace("</urlset>",r.reduce((e,{loc:t,lastmod:r,changefreq:a,priority:o})=>(process&&process.env&&process.env.COMPILE,e+`\n    <url>\n      <loc>${t.length?(0,i.urljoin)(n.default.SITE.CANONICAL,t):n.default.SITE.CANONICAL}</loc>\n      <lastmod>${(0,s.format)(r,"yyyy-MM-dd")}</lastmod>\n      ${a?"<changefreq>"+a+"</changefreq>":""}\n      <priority>${o}</priority>\n   </url>`),"")+"</urlset>"))}},"./src/utils/index.js":
/*!****************************!*\
  !*** ./src/utils/index.js ***!
  \****************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),Object.defineProperty(t,"loadable",{enumerable:!0,get:function(){return a.default}}),Object.defineProperty(t,"urljoin",{enumerable:!0,get:function(){return n.default}});var a=o(r(/*! ./loadable */"./src/utils/loadable.js")),n=o(r(/*! ./urljoin */"./src/utils/urljoin.js"));function o(e){return e&&e.__esModule?e:{default:e}}},"./src/utils/isBackend.js":
/*!********************************!*\
  !*** ./src/utils/isBackend.js ***!
  \********************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.isBackend=void 0;const a="true"===(process&&process.env&&process.env.BACKEND||"true");t.isBackend=a},"./src/utils/loadable.js":
/*!*******************************!*\
  !*** ./src/utils/loadable.js ***!
  \*******************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=function(e){return(0,n.default)(e,{fallback:a.default.createElement(o.default,null)})};var a=s(r(/*! react */"react")),n=s(r(/*! @loadable/component */"@loadable/component")),o=s(r(/*! ../site/Loading */"./src/site/Loading.js"));function s(e){return e&&e.__esModule?e:{default:e}}},"./src/utils/urljoin.js":
/*!******************************!*\
  !*** ./src/utils/urljoin.js ***!
  \******************************/
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var a=function(...e){let t,r;return r="*"!=e[-1]||e[-1].endsWith("/")?"/":"",t=e[0].startsWith("http")||e[0].startsWith("/")?"":"/",t+e.join("/")+r};t.default=a},0:
/*!***************************************!*\
  !*** multi ./src/sitemap/renderer.js ***!
  \***************************************/
/*! no static exports found */function(e,t,r){e.exports=r(/*! /home/adrian_villa/code/fwrlines/template-react-ssr/src/sitemap/renderer.js */"./src/sitemap/renderer.js")},"@apollo/client":
/*!*********************************!*\
  !*** external "@apollo/client" ***!
  \*********************************/
/*! no static exports found */function(e,t){e.exports=require("@apollo/client")},"@fwrlines/ds":
/*!*******************************!*\
  !*** external "@fwrlines/ds" ***!
  \*******************************/
/*! no static exports found */function(e,t){e.exports=require("@fwrlines/ds")},"@loadable/component":
/*!**************************************!*\
  !*** external "@loadable/component" ***!
  \**************************************/
/*! no static exports found */function(e,t){e.exports=require("@loadable/component")},"date-fns":
/*!***************************!*\
  !*** external "date-fns" ***!
  \***************************/
/*! no static exports found */function(e,t){e.exports=require("date-fns")},"graphql-tag":
/*!******************************!*\
  !*** external "graphql-tag" ***!
  \******************************/
/*! no static exports found */function(e,t){e.exports=require("graphql-tag")},"prop-types":
/*!*****************************!*\
  !*** external "prop-types" ***!
  \*****************************/
/*! no static exports found */function(e,t){e.exports=require("prop-types")},react:
/*!************************!*\
  !*** external "react" ***!
  \************************/
/*! no static exports found */function(e,t){e.exports=require("react")},"react-intl":
/*!*****************************!*\
  !*** external "react-intl" ***!
  \*****************************/
/*! no static exports found */function(e,t){e.exports=require("react-intl")},"react-router-dom":
/*!***********************************!*\
  !*** external "react-router-dom" ***!
  \***********************************/
/*! no static exports found */function(e,t){e.exports=require("react-router-dom")}});