module.exports=function(e){var t={};function a(r){if(t[r])return t[r].exports;var s=t[r]={i:r,l:!1,exports:{}};return e[r].call(s.exports,s,s.exports,a),s.l=!0,s.exports}return a.e=function(){return Promise.resolve()},a.m=e,a.c=t,a.d=function(e,t,r){a.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},a.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},a.t=function(e,t){if(1&t&&(e=a(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(a.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var s in e)a.d(r,s,function(t){return e[t]}.bind(null,s));return r},a.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return a.d(t,"a",t),t},a.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},a.p="/",a.oe=function(e){process.nextTick((function(){throw e}))},a(a.s=0)}({"./src/config/index.js":
/*!*****************************!*\
  !*** ./src/config/index.js ***!
  \*****************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t),t.default={SITE:{NAME:"",CANONICAL:"",GA:""},BUSINESS:{NAME:"",ADDRESS:"",ADDRESS_2:"",CITY:"",POSTCODE:""},SOCIAL_MEDIA:{FACEBOOK:"",TWITTER:"",INSTAGRAM:""}}},"./src/site/Loading.js":
/*!*****************************!*\
  !*** ./src/site/Loading.js ***!
  \*****************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t),a.d(t,"default",(function(){return n}));var r=a(/*! react */"react"),s=a.n(r);function n(){return s.a.createElement("h1",null,"A module is loading")}},"./src/site/auth/components/LoginButton/LoginButton.js":
/*!*************************************************************!*\
  !*** ./src/site/auth/components/LoginButton/LoginButton.js ***!
  \*************************************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds");function i(){return(i=Object.assign||function(e){for(var t=1;t<arguments.length;t++){var a=arguments[t];for(var r in a)Object.prototype.hasOwnProperty.call(a,r)&&(e[r]=a[r])}return e}).apply(this,arguments)}function l(e,t){if(null==e)return{};var a,r,s=function(e,t){if(null==e)return{};var a,r,s={},n=Object.keys(e);for(r=0;r<n.length;r++)a=n[r],t.indexOf(a)>=0||(s[a]=e[a]);return s}(e,t);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(e);for(r=0;r<n.length;r++)a=n[r],t.indexOf(a)>=0||Object.prototype.propertyIsEnumerable.call(e,a)&&(s[a]=e[a])}return s}var c=e=>{var{providerName:t,dataKey:a,query:s}=e,n=l(e,["providerName","dataKey","query"]);return r.createElement(o.OLoginButton,i({},n,{simple:!1,query:s,dataKey:a,providerName:t}))};c.propTypes={label:n.a.string,query:n.a.string,dataKey:n.a.string},c.defaultProps={query:"query {\n  oAuth2Google\n}\n",dataKey:"oAuth2Google"},t.default=c},"./src/site/auth/components/LoginButton/index.js":
/*!*******************************************************!*\
  !*** ./src/site/auth/components/LoginButton/index.js ***!
  \*******************************************************/
/*! exports provided: LoginButton */function(e,t,a){"use strict";a.r(t);var r=a(/*! ./LoginButton */"./src/site/auth/components/LoginButton/LoginButton.js");a.d(t,"LoginButton",(function(){return r.default}))},"./src/site/auth/components/Redeemer/Redeemer.js":
/*!*******************************************************!*\
  !*** ./src/site/auth/components/Redeemer/Redeemer.js ***!
  \*******************************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! react-router-dom */"react-router-dom"),n=a(/*! graphql-tag */"graphql-tag"),o=a.n(n),i=a(/*! @apollo/client */"@apollo/client"),l=a(/*! @fwrlines/ds */"@fwrlines/ds");t.default=e=>{var{code:t}=Object(s.useParams)(),a=Object(s.useHistory)(),[n,{data:{oAuth2Login:c}={},loading:u,error:d,called:h}]=Object(i.useMutation)(o()("mutation getJWT($code: String!) {\n  oAuth2Login(authorization_code: $code) {\n    access_token,\n    expires_in,\n    token_type\n  }\n}\n"),{variables:{code:t}});Object(r.useEffect)(()=>{!h&&t&&n()},[h,t,n]);var{setSessionCookie:p}=Object(r.useContext)(l.SessionContext);return Object(r.useEffect)(()=>{c&&(p(c.access_token,{maxAge:c.expires_in,secure:!("true"===(process&&process.env&&process.env.LOCAL||void 0))}),a.push("/"))},[a,p,c]),r.createElement(r.Fragment,null,r.createElement("h1",null,"We are redeeming a code to login"),r.createElement("pre",null,t))}},"./src/site/auth/components/Redeemer/index.js":
/*!****************************************************!*\
  !*** ./src/site/auth/components/Redeemer/index.js ***!
  \****************************************************/
/*! exports provided: Redeemer */function(e,t,a){"use strict";a.r(t);var r=a(/*! ./Redeemer */"./src/site/auth/components/Redeemer/Redeemer.js");a.d(t,"Redeemer",(function(){return r.default}))},"./src/site/auth/components/index.js":
/*!*******************************************!*\
  !*** ./src/site/auth/components/index.js ***!
  \*******************************************/
/*! exports provided: Redeemer, LoginButton */function(e,t,a){"use strict";a.r(t);var r=a(/*! ./Redeemer */"./src/site/auth/components/Redeemer/index.js");a.d(t,"Redeemer",(function(){return r.Redeemer}));var s=a(/*! ./LoginButton */"./src/site/auth/components/LoginButton/index.js");a.d(t,"LoginButton",(function(){return s.LoginButton}))},"./src/site/auth/index.js":
/*!********************************!*\
  !*** ./src/site/auth/index.js ***!
  \********************************/
/*! exports provided: routes, URLS */function(e,t,a){"use strict";a.r(t);var r=a(/*! ./routes */"./src/site/auth/routes.js");a.d(t,"routes",(function(){return r.default}));var s=a(/*! ./urls */"./src/site/auth/urls.js");a.d(t,"URLS",(function(){return s.default}))},"./src/site/auth/pages/Login.js":
/*!**************************************!*\
  !*** ./src/site/auth/pages/Login.js ***!
  \**************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i=a(/*! ../components */"./src/site/auth/components/index.js"),l=a(/*! react-router-dom */"react-router-dom"),c=a(/*! react-intl */"react-intl"),u=a(/*! ./messages */"./src/site/auth/pages/messages.js"),d={subtitle:r.createElement(c.FormattedMessage,u.default.loginSubtitle),heading:r.createElement(c.FormattedMessage,u.default.loginTitle),headingAs:"h1"},h=e=>{var{}=e,{isConnected:t,dashboardHomePath:a}=Object(r.useContext)(o.SessionContext),s=Object(l.useHistory)();return Object(r.useEffect)(()=>{t&&s.push(a)},[s,a,t]),r.createElement(o.Page,{id:"page_login"},r.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},r.createElement(o.Heading,d)),r.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},r.createElement(i.LoginButton,null)))};h.propTypes={someprop:n.a.node},t.default=h},"./src/site/auth/pages/Unauthorized.js":
/*!*********************************************!*\
  !*** ./src/site/auth/pages/Unauthorized.js ***!
  \*********************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i=a(/*! react-intl */"react-intl"),l=a(/*! ./messages */"./src/site/auth/pages/messages.js"),c={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},u={subtitle:r.createElement(i.FormattedMessage,l.default.unauthorizedSubtitle),heading:r.createElement(i.FormattedMessage,l.default.unauthorizedTitle),headingAs:"h1",label:"Error",labelClassName:"x-red basic"},d=e=>{var{}=e;return r.createElement(o.Page,{id:"page_unauthorized",itemType:"https://schema.org/FAQPage",HELMET:c},r.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},r.createElement(o.Heading,u)),r.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},r.createElement("p",null,r.createElement(i.FormattedMessage,l.default.unauthorizedExplanation)," ",r.createElement(o.SupportEmailLink,{label:r.createElement(i.FormattedMessage,l.default.unauthorizedContact)}))))};d.propTypes={someprop:n.a.node},t.default=d},"./src/site/auth/pages/messages.js":
/*!*****************************************!*\
  !*** ./src/site/auth/pages/messages.js ***!
  \*****************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react-intl */"react-intl"),s=Object(r.defineMessages)({loginTitle:{id:"app.auth.pages.login.title",defaultMessage:"Dashboard Access"},loginSubtitle:{id:"app.auth.pages.login.subtitle",defaultMessage:"Login below to your dashboard account"},unauthorizedTitle:{id:"app.auth.pages.unauthorized.title",defaultMessage:"Unauthorized"},unauthorizedSubtitle:{id:"app.auth.pages.unauthorized.subtitle",defaultMessage:"Your have sucessfully connected your account, but you are not allowed to log in."},unauthorizedExplanation:{id:"app.auth.pages.unauthorized.explanation",defaultMessage:"You can try to login with another account. Alternatively, if you believe this is a mistake"},unauthorizedContact:{id:"app.auth.pages.unauthorized.contact",defaultMessage:"you can contact support here."}});t.default=s},"./src/site/auth/routes.js":
/*!*********************************!*\
  !*** ./src/site/auth/routes.js ***!
  \*********************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! ../../utils */"./src/utils/index.js"),s=a(/*! ./urls */"./src/site/auth/urls.js"),n=a(/*! @fwrlines/ds */"@fwrlines/ds"),o=a.n(n),i="app.auth",l=":code([0-9a-z-]{64})";t.default=[{path:Object(r.urljoin)(s.default.REDEEM,l),component:Object(r.loadable)({resolved:{},chunkName:()=>"app.auth",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./components/Redeemer/Redeemer.js */"./src/site/auth/components/Redeemer/Redeemer.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./components/Redeemer/Redeemer.js */
return"./src/site/auth/components/Redeemer/Redeemer.js"}})},{path:s.default.LOGIN,component:Object(r.loadable)({resolved:{},chunkName:()=>"app.auth",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/Login.js */"./src/site/auth/pages/Login.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/Login.js */
return"./src/site/auth/pages/Login.js"}})},{path:s.default.LOGOUT,component:n.Logout,isPrivate:!0},{path:s.default.UNAUTHORIZED,component:Object(r.loadable)({resolved:{},chunkName:()=>"app.auth",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/Unauthorized.js */"./src/site/auth/pages/Unauthorized.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/Unauthorized.js */
return"./src/site/auth/pages/Unauthorized.js"}})}]},"./src/site/auth/urls.js":
/*!*******************************!*\
  !*** ./src/site/auth/urls.js ***!
  \*******************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);a(/*! ../../utils */"./src/utils/index.js");t.default={LOGIN:"/login",REDEEM:"/redeem",LOGOUT:"/logout",UNAUTHORIZED:"/unauthorized"}},"./src/site/dashboard/components/MyProfile.js":
/*!****************************************************!*\
  !*** ./src/site/dashboard/components/MyProfile.js ***!
  \****************************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! @fwrlines/ds */"@fwrlines/ds");a(/*! react-router-dom */"react-router-dom");t.default=e=>{var{}=e,{currentUserData:t={},currentUserLoading:a}=Object(r.useContext)(s.SessionContext);console.log("EXE => Consumer, context is",t);var n=t.oAuth2Profiles?t.oAuth2Profiles.find(e=>"google"==e.provider):{};return r.createElement(r.Fragment,null,t?r.createElement(r.Fragment,null,r.createElement(s.CircleInfo,{title:n.name,subtitle:n.email,className:"s3 k-s",image:n.picture,imageAlt:n.name})):"You are not connected")}},"./src/site/dashboard/components/ThemeSelector/ThemeSelector.js":
/*!**********************************************************************!*\
  !*** ./src/site/dashboard/components/ThemeSelector/ThemeSelector.js ***!
  \**********************************************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i=a(/*! react-intl */"react-intl"),l=a(/*! ./messages */"./src/site/dashboard/components/ThemeSelector/messages.js");a(/*! ./theme_selector.scss */"./src/site/dashboard/components/ThemeSelector/theme_selector.scss");a(/*! ../../../../utils/isBackend */"./src/utils/isBackend.js").isBackend||(console.log("This is not backend"),Promise.resolve().then(a.t.bind(null,/*! ./theme_selector.scss */"./src/site/dashboard/components/ThemeSelector/theme_selector.scss",7)));var c="theme_selector",u=[{value:"light",id:"light",label:r.createElement(i.FormattedMessage,l.default.lightTheme)},{value:"dark",id:"dark",label:r.createElement(i.FormattedMessage,l.default.darkTheme)},{value:"iceberg",id:"iceberg",label:"Iceberg"},{value:"system",id:"sys",label:r.createElement(i.FormattedMessage,l.default.systemTheme)}],d=e=>{var{id:t,className:a,style:s}=e,{preferredTheme:n,setPreferredTheme:d}=Object(r.useContext)(o.SiteContext);return r.createElement("span",{className:[c,"x-metadata c-x",a].filter(e=>e).join(" "),id:t,style:s},r.createElement("span",null,r.createElement(i.FormattedMessage,l.default.theme)," ",":"),r.createElement(o.DownshiftSelect,{inputId:"dashboard-theme-selector",options:u,aesthetic:"mars",setInputValue:d,value:n,style:{display:"inline-block",width:"auto"},buttonProps:{className:"x-subtitle",simple:!0,icon:"j",iconSide:"r"}}))};d.propTypes={id:n.a.string,className:n.a.string,style:n.a.object,children:n.a.node,as:n.a.oneOfType([n.a.string,n.a.object]),height:n.a.string,width:n.a.string},t.default=d},"./src/site/dashboard/components/ThemeSelector/index.js":
/*!**************************************************************!*\
  !*** ./src/site/dashboard/components/ThemeSelector/index.js ***!
  \**************************************************************/
/*! exports provided: ThemeSelector */function(e,t,a){"use strict";a.r(t);var r=a(/*! ./ThemeSelector */"./src/site/dashboard/components/ThemeSelector/ThemeSelector.js");a.d(t,"ThemeSelector",(function(){return r.default}))},"./src/site/dashboard/components/ThemeSelector/messages.js":
/*!*****************************************************************!*\
  !*** ./src/site/dashboard/components/ThemeSelector/messages.js ***!
  \*****************************************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react-intl */"react-intl"),s=Object(r.defineMessages)({lightTheme:{id:"app.dashboard.theme_selector.light_theme",defaultMessage:"Light"},darkTheme:{id:"app.dashboard.theme_selector.dark_theme",defaultMessage:"Dark"},systemTheme:{id:"app.dashboard.theme_selector.system_theme",defaultMessage:"System"},theme:{id:"app.dashboard.theme_selector.theme",defaultMessage:"Theme"}});t.default=s},"./src/site/dashboard/components/ThemeSelector/theme_selector.scss":
/*!*************************************************************************!*\
  !*** ./src/site/dashboard/components/ThemeSelector/theme_selector.scss ***!
  \*************************************************************************/
/*! no static exports found */function(e,t){},"./src/site/dashboard/components/index.js":
/*!************************************************!*\
  !*** ./src/site/dashboard/components/index.js ***!
  \************************************************/
/*! exports provided: MyProfile, ThemeSelector */function(e,t,a){"use strict";a.r(t);var r=a(/*! ./MyProfile */"./src/site/dashboard/components/MyProfile.js");a.d(t,"MyProfile",(function(){return r.default}));var s=a(/*! ./ThemeSelector */"./src/site/dashboard/components/ThemeSelector/index.js");a.d(t,"ThemeSelector",(function(){return s.ThemeSelector}))},"./src/site/dashboard/index.js":
/*!*************************************!*\
  !*** ./src/site/dashboard/index.js ***!
  \*************************************/
/*! exports provided: routes, URLS */function(e,t,a){"use strict";a.r(t);var r=a(/*! ./routes */"./src/site/dashboard/routes.js");a.d(t,"routes",(function(){return r.default}));var s=a(/*! ./urls */"./src/site/dashboard/urls.js");a.d(t,"URLS",(function(){return s.default}))},"./src/site/dashboard/layouts/Main.js":
/*!********************************************!*\
  !*** ./src/site/dashboard/layouts/Main.js ***!
  \********************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i=a(/*! ../components */"./src/site/dashboard/components/index.js");function l(e,t){if(null==e)return{};var a,r,s=function(e,t){if(null==e)return{};var a,r,s={},n=Object.keys(e);for(r=0;r<n.length;r++)a=n[r],t.indexOf(a)>=0||(s[a]=e[a]);return s}(e,t);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(e);for(r=0;r<n.length;r++)a=n[r],t.indexOf(a)>=0||Object.prototype.propertyIsEnumerable.call(e,a)&&(s[a]=e[a])}return s}var c=e=>{var{routes:t,navTree:a}=e,{userTheme:s}=(l(e,["routes","navTree"]),Object(r.useContext)(o.SiteContext));return r.createElement(o.DashboardContextProvider,null,r.createElement(o.DashboardNavigation,{tree:a,footer:r.createElement(i.ThemeSelector,null)}),r.createElement(o.DashboardMain,null,r.createElement(o.DashboardNavigation.HorizontalBar,{className:"md-h lg-h u50",label:"blah"}),r.createElement(o.SwitchRouteMap,{routes:t,NotFound:r.createElement("div",{style:{height:"120vh"}},"Content Goes here")})))};c.propTypes={routes:n.a.arrayOf(n.a.object),navTree:n.a.object},t.default=c},"./src/site/dashboard/layouts/index.js":
/*!*********************************************!*\
  !*** ./src/site/dashboard/layouts/index.js ***!
  \*********************************************/
/*! exports provided: MainLayout */function(e,t,a){"use strict";a.r(t);var r=a(/*! ./Main */"./src/site/dashboard/layouts/Main.js");a.d(t,"MainLayout",(function(){return r.default}))},"./src/site/dashboard/navigation/index.js":
/*!************************************************!*\
  !*** ./src/site/dashboard/navigation/index.js ***!
  \************************************************/
/*! exports provided: messages, tree */function(e,t,a){"use strict";a.r(t);var r=a(/*! ./messages */"./src/site/dashboard/navigation/messages.js");a.d(t,"messages",(function(){return r.default}));var s=a(/*! ./tree */"./src/site/dashboard/navigation/tree.js");a.d(t,"tree",(function(){return s.default}))},"./src/site/dashboard/navigation/messages.js":
/*!***************************************************!*\
  !*** ./src/site/dashboard/navigation/messages.js ***!
  \***************************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react-intl */"react-intl"),s=Object(r.defineMessages)({home:{id:"app.dashboard.navtree.home",defaultMessage:"Home"},account:{id:"app.dashboard.navtree.account",defaultMessage:"Account Information"},account_home:{id:"app.dashboard.navtree.account_home",defaultMessage:"Overview"},account_label:{id:"app.dashboard.navtree.account_label",defaultMessage:"Account"},account_google_integration:{id:"app.dashboard.navtree.account_google_integration",defaultMessage:"Google Account Link"},account_profile:{id:"app.dashboard.navtree.account_profile",defaultMessage:"My Profile"},billing:{id:"app.dashboard.navtree.billing",defaultMessage:"Plan and payment"},billing_home:{id:"app.dashboard.navtree.billing_home",defaultMessage:"General"},billing_payment:{id:"app.dashboard.navtree.billing_payment",defaultMessage:"Payment details"},billing_plan:{id:"app.dashboard.navtree.billing_plan",defaultMessage:"Plan details"},logout:{id:"app.dashboard.navtree.logout",defaultMessage:"Logout"},shop:{id:"app.dashboard.navtree.shop",defaultMessage:"My Shop"},shop_home:{id:"app.dashboard.navtree.shop_home",defaultMessage:"General"},shop_contact:{id:"app.dashboard.navtree.shop_contact",defaultMessage:"Public Information"},shop_hours:{id:"app.dashboard.navtree.shop_hours",defaultMessage:"Opening Hours"},website:{id:"app.dashboard.navtree.website",defaultMessage:"My Website"},website_pages:{id:"app.dashboard.navtree.website_pages",defaultMessage:"Pages"}});t.default=s},"./src/site/dashboard/navigation/tree.js":
/*!***********************************************!*\
  !*** ./src/site/dashboard/navigation/tree.js ***!
  \***********************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! ../urls */"./src/site/dashboard/urls.js"),n=a(/*! ../../urls */"./src/site/urls.js"),o=a(/*! react-intl */"react-intl"),i=a(/*! ./messages */"./src/site/dashboard/navigation/messages.js");t.default={title:"WebOffice",pathname:s.default.HOME,subItems:[{title:r.createElement(o.FormattedMessage,i.default.home),pathname:s.default.HOME},{section:"WebOfficina",title:r.createElement(o.FormattedMessage,i.default.website),pathname:s.default.WEBSITE_HOME},{section:"WebOfficina",title:r.createElement(o.FormattedMessage,i.default.shop),pathname:s.default.SHOP_HOME,subItems:[{title:r.createElement(o.FormattedMessage,i.default.shop_hours),pathname:s.default.SHOP_HOURS},{title:r.createElement(o.FormattedMessage,i.default.shop_contact),pathname:s.default.SHOP_CONTACT}]},{section:r.createElement(o.FormattedMessage,i.default.account_label),title:r.createElement(o.FormattedMessage,i.default.account),pathname:s.default.ACCOUNT_HOME,logo:"/illustrations/iso-computer.png",subItems:[{title:r.createElement(o.FormattedMessage,i.default.account_home),pathname:s.default.ACCOUNT_HOME},{title:r.createElement(o.FormattedMessage,i.default.account_profile),pathname:s.default.ACCOUNT_PROFILE},{title:r.createElement(o.FormattedMessage,i.default.account_google_integration),pathname:s.default.ACCOUNT_GOOGLE_INTEGRATION}]},{section:r.createElement(o.FormattedMessage,i.default.account_label),title:r.createElement(o.FormattedMessage,i.default.billing),pathname:s.default.PLAN_HOME,subItems:[{title:r.createElement(o.FormattedMessage,i.default.billing_home),pathname:s.default.PLAN_HOME},{title:r.createElement(o.FormattedMessage,i.default.billing_plan),pathname:s.default.PLAN_DETAILS},{title:r.createElement(o.FormattedMessage,i.default.billing_payment),pathname:s.default.PLAN_PAYMENT}]},{section:r.createElement(o.FormattedMessage,i.default.account_label),title:r.createElement(o.FormattedMessage,i.default.logout),pathname:n.AUTH.LOGOUT}]}},"./src/site/dashboard/pages/AccountGoogleIntegration.js":
/*!**************************************************************!*\
  !*** ./src/site/dashboard/pages/AccountGoogleIntegration.js ***!
  \**************************************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},l={subtitle:"A place to edit data",heading:"Google Integration",headingAs:"h1"},c=e=>{var{history:t,location:a,match:s}=e;return r.createElement(o.Page,{id:"page_account_google_integration",itemType:"https://schema.org/FAQPage",HELMET:i},r.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},r.createElement(o.Heading,l)),r.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")),r.createElement(o.Page.Section,{id:"a2",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")))};c.propTypes={someprop:n.a.node},t.default=c},"./src/site/dashboard/pages/AccountHome.js":
/*!*************************************************!*\
  !*** ./src/site/dashboard/pages/AccountHome.js ***!
  \*************************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},l={subtitle:"A place to edit data",heading:"Account : general",headingAs:"h1"},c=e=>{var{history:t,location:a,match:s}=e;return r.createElement(o.Page,{id:"page_account_home",itemType:"https://schema.org/FAQPage",HELMET:i},r.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},r.createElement(o.Heading,l)),r.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")),r.createElement(o.Page.Section,{id:"a2",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")))};c.propTypes={someprop:n.a.node},t.default=c},"./src/site/dashboard/pages/Home.js":
/*!******************************************!*\
  !*** ./src/site/dashboard/pages/Home.js ***!
  \******************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},l={subtitle:"A place to edit data",heading:"Home",headingAs:"h1"},c=e=>{var{history:t,location:a,match:s}=e;return r.createElement(o.Page,{id:"page_home",itemType:"https://schema.org/FAQPage",HELMET:i},r.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},r.createElement(o.Heading,l)),r.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")),r.createElement(o.Page.Section,{id:"a2",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")))};c.propTypes={someprop:n.a.node},t.default=c},"./src/site/dashboard/pages/PlanDetails.js":
/*!*************************************************!*\
  !*** ./src/site/dashboard/pages/PlanDetails.js ***!
  \*************************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},l={subtitle:"A place to edit data",heading:"Shop Details",headingAs:"h1"},c=e=>{var{history:t,location:a,match:s}=e;return r.createElement(o.Page,{id:"page_account_plan_details",itemType:"https://schema.org/FAQPage",HELMET:i},r.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},r.createElement(o.Heading,l)),r.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")),r.createElement(o.Page.Section,{id:"a2",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")))};c.propTypes={someprop:n.a.node},t.default=c},"./src/site/dashboard/pages/PlanHome.js":
/*!**********************************************!*\
  !*** ./src/site/dashboard/pages/PlanHome.js ***!
  \**********************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},l={subtitle:"A place to edit data",heading:"Plan Home",headingAs:"h1"},c=e=>{var{history:t,location:a,match:s}=e;return r.createElement(o.Page,{id:"page_account_plan_home",itemType:"https://schema.org/FAQPage",HELMET:i},r.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},r.createElement(o.Heading,l)),r.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")),r.createElement(o.Page.Section,{id:"a2",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")))};c.propTypes={someprop:n.a.node},t.default=c},"./src/site/dashboard/pages/PlanPayment.js":
/*!*************************************************!*\
  !*** ./src/site/dashboard/pages/PlanPayment.js ***!
  \*************************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},l={subtitle:"A place to edit data",heading:"Plan Payment",headingAs:"h1"},c=e=>{var{history:t,location:a,match:s}=e;return r.createElement(o.Page,{id:"page_account_plan_payment",itemType:"https://schema.org/FAQPage",HELMET:i},r.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},r.createElement(o.Heading,l)),r.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")),r.createElement(o.Page.Section,{id:"a2",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")))};c.propTypes={someprop:n.a.node},t.default=c},"./src/site/dashboard/pages/Profile.js":
/*!*********************************************!*\
  !*** ./src/site/dashboard/pages/Profile.js ***!
  \*********************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i=a(/*! ../components */"./src/site/dashboard/components/index.js"),l={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},c={subtitle:"In this page you can view and modify information related to your profile on this website.",heading:"My Profile",headingClassName:"ts-green",headingAs:"h1"},u=e=>{var{history:t,location:a,match:s}=e;return r.createElement(o.Page,{id:"page_profile",itemType:"https://schema.org/FAQPage",HELMET:l},r.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},r.createElement(o.Heading,c)),r.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},r.createElement(i.MyProfile,null)),r.createElement(o.Page.Section,{id:"a2",className:"p-u u2"},r.createElement("p",null,"Here a form to edit your data")))};u.propTypes={someprop:n.a.node},t.default=u},"./src/site/dashboard/pages/ShopContact.js":
/*!*************************************************!*\
  !*** ./src/site/dashboard/pages/ShopContact.js ***!
  \*************************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},l={className:"uc",subtitle:"Stanley Kubrick, 1960",heading:"Spartacus",headingClassName:"ts-green",headingAs:"h1",label:"Film",labelClassName:"x-red basic"},c=e=>{var{history:t,location:a,match:s}=e;return r.createElement(o.Page,{id:"page_shop_contact",itemType:"https://schema.org/FAQPage",HELMET:i},r.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},r.createElement(o.Heading,l)),r.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")),r.createElement(o.Page.Section,{id:"a2",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")))};c.propTypes={someprop:n.a.node},t.default=c},"./src/site/dashboard/pages/ShopDetails.js":
/*!*************************************************!*\
  !*** ./src/site/dashboard/pages/ShopDetails.js ***!
  \*************************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},l={subtitle:"A place to edit data",heading:"Shop Details",headingAs:"h1"},c=e=>{var{history:t,location:a,match:s}=e;return r.createElement(o.Page,{id:"page_shop_details",itemType:"https://schema.org/FAQPage",HELMET:i},r.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},r.createElement(o.Heading,l)),r.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")),r.createElement(o.Page.Section,{id:"a2",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")))};c.propTypes={someprop:n.a.node},t.default=c},"./src/site/dashboard/pages/ShopHome.js":
/*!**********************************************!*\
  !*** ./src/site/dashboard/pages/ShopHome.js ***!
  \**********************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},l={subtitle:"A place to edit data",heading:"Shop Home",headingAs:"h1"},c=e=>{var{history:t,location:a,match:s}=e;return r.createElement(o.Page,{id:"page_shop_home",itemType:"https://schema.org/FAQPage",HELMET:i},r.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},r.createElement(o.Heading,l)),r.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")),r.createElement(o.Page.Section,{id:"a2",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")))};c.propTypes={someprop:n.a.node},t.default=c},"./src/site/dashboard/pages/ShopHours.js":
/*!***********************************************!*\
  !*** ./src/site/dashboard/pages/ShopHours.js ***!
  \***********************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},l={className:"uc",subtitle:"Stanley Kubrick, 1960",heading:"Spartacus",headingClassName:"ts-green",headingAs:"h1",label:"Film",labelClassName:"x-red basic"},c=e=>{var{history:t,location:a,match:s}=e;return r.createElement(o.Page,{id:"page_shop_hours",itemType:"https://schema.org/FAQPage",HELMET:i},r.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},r.createElement(o.Heading,l)),r.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")),r.createElement(o.Page.Section,{id:"a2",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")))};c.propTypes={someprop:n.a.node},t.default=c},"./src/site/dashboard/pages/WebsiteHome.js":
/*!*************************************************!*\
  !*** ./src/site/dashboard/pages/WebsiteHome.js ***!
  \*************************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a(/*! prop-types */"prop-types"),n=a.n(s),o=a(/*! @fwrlines/ds */"@fwrlines/ds"),i={robots:"noindex, nofollow",title:"test of the title",title_tag:"this should appear in the title tag"},l={subtitle:"A place to edit data",heading:"Website Home",headingAs:"h1"},c=e=>{var{history:t,location:a,match:s}=e;return r.createElement(o.Page,{id:"page_website_home",itemType:"https://schema.org/FAQPage",HELMET:i},r.createElement(o.Page.Section,{head:!0,className:"p-u u2",id:"head"},r.createElement(o.Heading,l)),r.createElement(o.Page.Section,{id:"a1",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")),r.createElement(o.Page.Section,{id:"a2",className:"p-u u2"},r.createElement("h2",null,"Section A2"),r.createElement("p",null,"Some content here. Blah blah")))};c.propTypes={someprop:n.a.node},t.default=c},"./src/site/dashboard/routes.js":
/*!**************************************!*\
  !*** ./src/site/dashboard/routes.js ***!
  \**************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! react */"react"),s=a.n(r),n=a(/*! ../../utils */"./src/utils/index.js"),o=a(/*! ./layouts */"./src/site/dashboard/layouts/index.js"),i=a(/*! ./navigation */"./src/site/dashboard/navigation/index.js"),l=a(/*! ./urls */"./src/site/dashboard/urls.js");function c(){return(c=Object.assign||function(e){for(var t=1;t<arguments.length;t++){var a=arguments[t];for(var r in a)Object.prototype.hasOwnProperty.call(a,r)&&(e[r]=a[r])}return e}).apply(this,arguments)}var u="app.dashboard",d=[{path:l.default.HOME,component:Object(n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/Home.js */"./src/site/dashboard/pages/Home.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/Home.js */
return"./src/site/dashboard/pages/Home.js"}}),exact:!0,isPrivate:!0},{path:l.default.PROFILE,component:Object(n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/Profile.js */"./src/site/dashboard/pages/Profile.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/Profile.js */
return"./src/site/dashboard/pages/Profile.js"}}),exact:!0,isPrivate:!0},{path:l.default.WEBSITE_HOME,component:Object(n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/WebsiteHome.js */"./src/site/dashboard/pages/WebsiteHome.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/WebsiteHome.js */
return"./src/site/dashboard/pages/WebsiteHome.js"}}),exact:!0,isPrivate:!0},{path:l.default.SHOP_HOME,component:Object(n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/ShopHome.js */"./src/site/dashboard/pages/ShopHome.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/ShopHome.js */
return"./src/site/dashboard/pages/ShopHome.js"}}),exact:!0,isPrivate:!0},{path:l.default.SHOP_DETAILS,component:Object(n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/ShopDetails.js */"./src/site/dashboard/pages/ShopDetails.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/ShopDetails.js */
return"./src/site/dashboard/pages/ShopDetails.js"}}),exact:!0,isPrivate:!0},{path:l.default.SHOP_HOURS,component:Object(n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/ShopHours.js */"./src/site/dashboard/pages/ShopHours.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/ShopHours.js */
return"./src/site/dashboard/pages/ShopHours.js"}}),exact:!0,isPrivate:!0},{path:l.default.SHOP_CONTACT,component:Object(n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/ShopContact.js */"./src/site/dashboard/pages/ShopContact.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/ShopContact.js */
return"./src/site/dashboard/pages/ShopContact.js"}}),exact:!0,isPrivate:!0},{path:l.default.ACCOUNT_HOME,component:Object(n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/AccountHome.js */"./src/site/dashboard/pages/AccountHome.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/AccountHome.js */
return"./src/site/dashboard/pages/AccountHome.js"}}),exact:!0,isPrivate:!0},{path:l.default.ACCOUNT_PROFILE,component:Object(n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/Profile.js */"./src/site/dashboard/pages/Profile.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/Profile.js */
return"./src/site/dashboard/pages/Profile.js"}}),exact:!0,isPrivate:!0},{path:l.default.ACCOUNT_GOOGLE_INTEGRATION,component:Object(n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/AccountGoogleIntegration.js */"./src/site/dashboard/pages/AccountGoogleIntegration.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/AccountGoogleIntegration.js */
return"./src/site/dashboard/pages/AccountGoogleIntegration.js"}}),exact:!0,isPrivate:!0},{path:l.default.PLAN_HOME,component:Object(n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/PlanHome.js */"./src/site/dashboard/pages/PlanHome.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/PlanHome.js */
return"./src/site/dashboard/pages/PlanHome.js"}}),exact:!0,isPrivate:!0},{path:l.default.PLAN_DETAILS,component:Object(n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/PlanDetails.js */"./src/site/dashboard/pages/PlanDetails.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/PlanDetails.js */
return"./src/site/dashboard/pages/PlanDetails.js"}}),exact:!0,isPrivate:!0},{path:l.default.PLAN_PAYMENT,component:Object(n.loadable)({resolved:{},chunkName:()=>"app.dashboard",isReady(e){var t=this.resolve(e);return!1!==this.resolved[t]&&!!a.m[t]},importAsync:()=>Promise.resolve().then(a.bind(null,/*! ./pages/PlanPayment.js */"./src/site/dashboard/pages/PlanPayment.js")),requireAsync(e){var t=this.resolve(e);return this.resolved[t]=!1,this.importAsync(e).then(e=>(this.resolved[t]=!0,e))},requireSync(e){var t=this.resolve(e);return a(t)},resolve(){/*! ./pages/PlanPayment.js */
return"./src/site/dashboard/pages/PlanPayment.js"}}),exact:!0,isPrivate:!0}];t.default=[{path:l.default.all,render:e=>r.createElement(o.MainLayout,c({routes:d,navTree:i.tree},e))}]},"./src/site/dashboard/urls.js":
/*!************************************!*\
  !*** ./src/site/dashboard/urls.js ***!
  \************************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! ../../utils */"./src/utils/index.js");t.default={basePath:"/d/",all:Object(r.urljoin)("/d/","*"),HOME:"/d/",WEBSITE_HOME:Object(r.urljoin)("/d/","/website/"),SHOP_HOME:Object(r.urljoin)("/d/","/shop/"),SHOP_DETAILS:Object(r.urljoin)("/d/","/shop/","details"),SHOP_HOURS:Object(r.urljoin)("/d/","/shop/","opening-hours"),SHOP_CONTACT:Object(r.urljoin)("/d/","/shop/","contact"),ACCOUNT_HOME:Object(r.urljoin)("/d/","/account/"),ACCOUNT_PROFILE:Object(r.urljoin)("/d/","/account/","profile"),ACCOUNT_GOOGLE_INTEGRATION:Object(r.urljoin)("/d/","/account/","google"),PLAN_HOME:Object(r.urljoin)("/d/","/plan/"),PLAN_DETAILS:Object(r.urljoin)("/d/","/plan/","details"),PLAN_PAYMENT:Object(r.urljoin)("/d/","/plan/","billing"),PROFILE:Object(r.urljoin)("/d/","profile"),PROFILE2:Object(r.urljoin)("/d/","profile2")}},"./src/site/urls.js":
/*!**************************!*\
  !*** ./src/site/urls.js ***!
  \**************************/
/*! exports provided: DASHBOARD, AUTH, STATIC */function(e,t,a){"use strict";a.r(t),a.d(t,"STATIC",(function(){return n}));var r=a(/*! ./dashboard */"./src/site/dashboard/index.js");a.d(t,"DASHBOARD",(function(){return r.URLS}));var s=a(/*! ./auth */"./src/site/auth/index.js");a.d(t,"AUTH",(function(){return s.URLS}));var n={HOME:"",ANOTHERPAGE:"longer/url/for/sitemap"}},"./src/sitemap/renderer.js":
/*!*********************************!*\
  !*** ./src/sitemap/renderer.js ***!
  \*********************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t);var r=a(/*! ../config */"./src/config/index.js"),s=a(/*! ../site/urls */"./src/site/urls.js"),n=a(/*! date-fns */"date-fns"),o=a(/*! ../utils */"./src/utils/index.js");function i(e,t,a,r,s,n,o){try{var i=e[n](o),l=i.value}catch(e){return void a(e)}i.done?t(l):Promise.resolve(l).then(r,s)}var l={HOME:{changefreq:"yearly",priority:.5,lastmod:new Date("2019-10-02")},ANOTHERPAGE:{changefreq:"daily",priority:.5,lastmod:new Date("2019-09-12")}};t.default=function(){var e,t=(e=function*(e,t){new Date;var a=[];return Object.keys(s.STATIC).forEach(e=>{var{changefreq:t,priority:r,lastmod:n}=l[e],o=s.STATIC[e];a.push({loc:o,lastmod:n,changefreq:t,priority:r})}),t.setHeader("Content-Type","text/xml"),t.send('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n</urlset> \n'.replace("</urlset>",a.reduce((e,t)=>{var{loc:a,lastmod:s,changefreq:i,priority:l}=t;return process&&process.env&&process.env.COMPILE,e+"\n    <url>\n      <loc>".concat(a.length?Object(o.urljoin)(r.default.SITE.CANONICAL,a):r.default.SITE.CANONICAL,"</loc>\n      <lastmod>").concat(Object(n.format)(s,"yyyy-MM-dd"),"</lastmod>\n      ").concat(i?"<changefreq>"+i+"</changefreq>":"","\n      <priority>").concat(l,"</priority>\n   </url>")},"")+"</urlset>"))},function(){var t=this,a=arguments;return new Promise((function(r,s){var n=e.apply(t,a);function o(e){i(n,r,s,o,l,"next",e)}function l(e){i(n,r,s,o,l,"throw",e)}o(void 0)}))});return function(e,a){return t.apply(this,arguments)}}()},"./src/utils/index.js":
/*!****************************!*\
  !*** ./src/utils/index.js ***!
  \****************************/
/*! exports provided: loadable, urljoin */function(e,t,a){"use strict";a.r(t);var r=a(/*! ./loadable */"./src/utils/loadable.js");a.d(t,"loadable",(function(){return r.default}));var s=a(/*! ./urljoin */"./src/utils/urljoin.js");a.d(t,"urljoin",(function(){return s.default}))},"./src/utils/isBackend.js":
/*!********************************!*\
  !*** ./src/utils/isBackend.js ***!
  \********************************/
/*! exports provided: isBackend */function(e,t,a){"use strict";a.r(t),a.d(t,"isBackend",(function(){return r}));var r="true"===(process&&process.env&&process.env.BACKEND||"true")},"./src/utils/loadable.js":
/*!*******************************!*\
  !*** ./src/utils/loadable.js ***!
  \*******************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t),a.d(t,"default",(function(){return l}));var r=a(/*! react */"react"),s=a.n(r),n=a(/*! @loadable/component */"@loadable/component"),o=a.n(n),i=a(/*! ../site/Loading */"./src/site/Loading.js");function l(e){return o()(e,{fallback:s.a.createElement(i.default,null)})}},"./src/utils/urljoin.js":
/*!******************************!*\
  !*** ./src/utils/urljoin.js ***!
  \******************************/
/*! exports provided: default */function(e,t,a){"use strict";a.r(t),t.default=function(){for(var e,t=arguments.length,a=new Array(t),r=0;r<t;r++)a[r]=arguments[r];return e="*"!=a[-1]||a[-1].endsWith("/")?"/":"",(a[0].startsWith("http")||a[0].startsWith("/")?"":"/")+a.join("/")+e}},0:
/*!***************************************!*\
  !*** multi ./src/sitemap/renderer.js ***!
  \***************************************/
/*! no static exports found */function(e,t,a){e.exports=a(/*! /home/adrian_villa/code/fwrlines/template-react-ssr/src/sitemap/renderer.js */"./src/sitemap/renderer.js")},"@apollo/client":
/*!*********************************!*\
  !*** external "@apollo/client" ***!
  \*********************************/
/*! no static exports found */function(e,t){e.exports=require("@apollo/client")},"@fwrlines/ds":
/*!*******************************!*\
  !*** external "@fwrlines/ds" ***!
  \*******************************/
/*! no static exports found */function(e,t){e.exports=require("@fwrlines/ds")},"@loadable/component":
/*!**************************************!*\
  !*** external "@loadable/component" ***!
  \**************************************/
/*! no static exports found */function(e,t){e.exports=require("@loadable/component")},"date-fns":
/*!***************************!*\
  !*** external "date-fns" ***!
  \***************************/
/*! no static exports found */function(e,t){e.exports=require("date-fns")},"graphql-tag":
/*!******************************!*\
  !*** external "graphql-tag" ***!
  \******************************/
/*! no static exports found */function(e,t){e.exports=require("graphql-tag")},"prop-types":
/*!*****************************!*\
  !*** external "prop-types" ***!
  \*****************************/
/*! no static exports found */function(e,t){e.exports=require("prop-types")},react:
/*!************************!*\
  !*** external "react" ***!
  \************************/
/*! no static exports found */function(e,t){e.exports=require("react")},"react-intl":
/*!*****************************!*\
  !*** external "react-intl" ***!
  \*****************************/
/*! no static exports found */function(e,t){e.exports=require("react-intl")},"react-router-dom":
/*!***********************************!*\
  !*** external "react-router-dom" ***!
  \***********************************/
/*! no static exports found */function(e,t){e.exports=require("react-router-dom")}});